### ISSUE TITLE
show a error when add 'jalali_date', in settings.py 

### ISSUE THREAD

**Issue by meysamk7918** [a-roomana/django-jalali-date#83]
Hi, I have a problem.
After installing this package, when I want to add it to my project settings.py , I get an error

`Traceback (most recent call last):
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\utils.py", line 69, in __getitem__
    return self._engines[alias]
           ~~~~~~~~~~~~~^^^^^^^
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\backends\django.py", line 128, in get_package_libraries
    module = import_module(entry[1])
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHAYAN\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\jalali_date\templatetags\jalali_tags.py", line 2, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SHAYAN\Desktop\Ann\Ann\manage.py", line 22, in <module>
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\utils.py", line 69, in __getitem__
    main()
  File "C:\Users\SHAYAN\Desktop\Ann\Ann\manage.py", line 18, in main
    return self._engines[alias]
           ~~~~~~~~~~~~~^^^^^^^
KeyError: 'django'
    execute_from_command_line(sys.argv)
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\backends\django.py", line 128, in get_package_libraries
    utility.execute()
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    module = import_module(entry[1])
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHAYAN\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\core\management\commands\runserver.py", line 74, in execute
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    super().execute(*args, **options)
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\core\management\base.py", line 459, in execute
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    output = self.handle(*args, **options)
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\jalali_date\templatetags\jalali_tags.py", line 2, in <module>
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    from distutils.version import StrictVersion
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\core\management\commands\runserver.py", line 111, in handle
ModuleNotFoundError: No module named 'distutils'

The above exception was the direct cause of the following exception:

    self.run(**options)
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\core\management\commands\runserver.py", line 118, in run
Traceback (most recent call last):
  File "C:\Users\SHAYAN\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\utils\autoreload.py", line 671, in run_with_reloader
    self.run()
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Users\SHAYAN\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\utils\autoreload.py", line 660, in start_django
    self._target(*self._args, **self._kwargs)
    reloader.run(django_main_thread)
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\utils\autoreload.py", line 343, in run
    fn(*args, **kwargs)
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    autoreload_started.send(sender=self)
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    self.check(display_num_errors=True)
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\core\management\base.py", line 486, in check
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\autoreload.py", line 50, in watch_for_template_changes
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    for directory in get_template_directories():
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\autoreload.py", line 16, in get_template_directories
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\contrib\admin\checks.py", line 79, in check_dependencies
    for backend in engines.all():
                   ^^^^^^^^^^^^^
    for engine in engines.all():
                  ^^^^^^^^^^^^^
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\utils.py", line 94, in all
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\utils.py", line 94, in all
    return [self[alias] for alias in self]
    return [self[alias] for alias in self]
            ~~~~^^^^^^^
            ~~~~^^^^^^^
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\utils.py", line 85, in __getitem__
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\utils.py", line 85, in __getitem__
    engine = engine_cls(params)
             ^^^^^^^^^^^^^^^^^^
    engine = engine_cls(params)
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\backends\django.py", line 24, in __init__
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\backends\django.py", line 24, in __init__
    options["libraries"] = self.get_templatetag_libraries(libraries)
    options["libraries"] = self.get_templatetag_libraries(libraries)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\backends\django.py", line 42, in get_templatetag_libraries
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\backends\django.py", line 42, in get_templatetag_libraries
    libraries = get_installed_libraries()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\backends\django.py", line 116, in get_installed_libraries
    libraries = get_installed_libraries()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\backends\django.py", line 116, in get_installed_libraries
    return {
           ^
    return {
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\backends\django.py", line 105, in get_template_tag_modules
           ^
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\backends\django.py", line 105, in get_template_tag_modules
    for name in get_package_libraries(pkg):
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\backends\django.py", line 130, in get_package_libraries
    for name in get_package_libraries(pkg):
  File "C:\Users\SHAYAN\Desktop\Ann\venv\Lib\site-packages\django\template\backends\django.py", line 130, in get_package_libraries
    raise InvalidTemplateLibrary(
    raise InvalidTemplateLibrary(
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'jalali_date.templatetags.jalali_tags': No 
module named 'distutils'
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'jalali_date.templatetags.jalali_tags': No 
module named 'distutils'`

**Comment by meysamk7918** [comment]
مشکلم با نصب setuptools حل شد . در نسخه 3.12 پایتون این مشکل به دلیل نصب نبودن distutils به وجود میاد
 pip install setuptools
